### ISSUE TITLE
Error in printer.js

### ISSUE THREAD

**Issue by fabien** [alevroub/prettier-plugin-groq#1]
Hi @alevroub thanks for making this available, it's been invaluable to debug some query issues I was having.

However, in order for it to work, I had to change this line:

https://github.com/alevroub/prettier-plugin-groq/blob/8335bc2c43277641b27427edca21506465b4e93f/src/printer.js#L26

Into: `: String(node.value);` because I was getting `cannot call toString() on null` errors.

Could you please have a look? Thanks!

**Comment by alejandrovrojas** [comment]
Thanks! You're right, I forgot to test null values more thoroughly. Fixed in `0.2.3`
